// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfLCbz9pqmZnqM8KfGqMUxmloru5P-GNI',
    appId: '1:237619997785:web:a28109ee54a8e32b33d548',
    messagingSenderId: '237619997785',
    projectId: 'studentenrollment-f9862',
    authDomain: 'studentenrollment-f9862.firebaseapp.com',
    storageBucket: 'studentenrollment-f9862.firebasestorage.app',
    measurementId: 'G-05EVXZ7NQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-fTXC6gANrlR1QJiEEsBaQCCOQT-sFUo',
    appId: '1:237619997785:android:df58eb6472223af333d548',
    messagingSenderId: '237619997785',
    projectId: 'studentenrollment-f9862',
    storageBucket: 'studentenrollment-f9862.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3-JmgSdQi8XUOSFbNTtCArQzq8shOEI',
    appId: '1:237619997785:ios:27c2d6cd931f0bd533d548',
    messagingSenderId: '237619997785',
    projectId: 'studentenrollment-f9862',
    storageBucket: 'studentenrollment-f9862.firebasestorage.app',
    iosBundleId: 'com.example.studentEnrollment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj3-JmgSdQi8XUOSFbNTtCArQzq8shOEI',
    appId: '1:237619997785:ios:27c2d6cd931f0bd533d548',
    messagingSenderId: '237619997785',
    projectId: 'studentenrollment-f9862',
    storageBucket: 'studentenrollment-f9862.firebasestorage.app',
    iosBundleId: 'com.example.studentEnrollment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfLCbz9pqmZnqM8KfGqMUxmloru5P-GNI',
    appId: '1:237619997785:web:816a3fdf65965c2933d548',
    messagingSenderId: '237619997785',
    projectId: 'studentenrollment-f9862',
    authDomain: 'studentenrollment-f9862.firebaseapp.com',
    storageBucket: 'studentenrollment-f9862.firebasestorage.app',
    measurementId: 'G-6V9YSW8KJH',
  );

}